name: Quarto Publish

on:
  push:
    branches: main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render Quarto Project
        run: quarto render computations.qmd

      - name: Upload rendered HTML
        uses: actions/upload-artifact@v3
        with:
          name: computations-html
          path: computations.html

