name: Render Quarto document

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: quarto-dev/quarto-actions/setup@v2
      - name: Render document
        run: quarto render computations.qmd
      - uses: actions/upload-artifact@v3
        with:
          name: computations-html
          path: computations.html
